/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -T rocket.glb 
Files: rocket.glb [669.1KB] > rocket-transformed.glb [40.96KB] (94%)
Author: Xeno_ (https://sketchfab.com/Xeno_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-b3d6da919f3e40238262611d71329a93
Title: Rocket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Rocket(props) {
  const { nodes, materials } = useGLTF('/gltf/rocket-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        position={[-0.01, 2.724, 0]}
        scale={[0.383, 1.196, 0.383]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.PaletteMaterial002}
        position={[-0.01, 2.724, 0]}
        scale={[0.383, 1.196, 0.383]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials['Material.004']}
        position={[-0.01, 2.724, 0]}
        scale={[0.383, 1.196, 0.383]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.PaletteMaterial003}
        position={[-0.011, 4.854, -0.001]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.024, 0.024, 0.024]}
      />
    </group>
  )
}

useGLTF.preload('/gltf/rocket-transformed.glb')
